### ISSUE TITLE
Background color problems

### ISSUE THREAD

**Issue by kopr12** [Airblader/i3blocks-gaps#3]
i3-gaps version is 4.13 , i3blocks-gaps 1.4

I was trying and trying, searched around and I just can't make this work, point is to change the background color of some block, can someone please tell me what I need to do to make this work ?

This works :

```
[example]
full_text="example"
color=#FFFFFF
```

This produce error :
```
[example]
full_text="example"
color=#FFFFFF
background=#222222
```

Thanks.

**Comment by Airblader** [comment]
What error?

**Comment by kopr12** [comment]
Error: status_command process exited unexpectedly (exit 1)

**Comment by Airblader** [comment]
What does just running `i3blocks´ from a terminal output? How did you install i3blocks-gaps? Are you sure you installed the fork?

**Comment by kopr12** [comment]
i3blocks terminal output :
```
ERROR try_parse:192: fopen: No such file or directory
ERROR main:70: Try 'i3blocks -h' for more information.
```

I've installed i3blocks-gaps from the package , yes I'm sure (I can see the gaps :) ), everything is working fine but that background color.

**Comment by Airblader** [comment]
> I've installed i3blocks-gaps from the package , yes I'm sure (I can see the gaps :) )

Gaps come from i3-gaps, not from i3blocks-gaps. What package did you use for i3blocks-gaps? The AUR package (`i3blocks-gaps-git`?)

And just to be clear, simply removing the `background` line from the config and `i3blocks` from the terminal doesn't produce that error?

**Comment by kopr12** [comment]
That's what I meant, sorry.
Both packages are gaps (i3blocks-gaps, i3-gaps) , i3 and i3blocks packages were uninstalled prior to installing gaps.
I'm on Gentoo, do I need latest from git maybe ? I didn't try that, but I can.

Yes, commenting that "background" line and then reloading works fine, blocks are shown and there is no error.
If I remove comment blocks are not shown, instead there is error message in i3bar.

**Comment by Airblader** [comment]
Yeah, please install i3blocks-gaps from git (i3-gaps you don't need to do that). I never actually made any kind of release for i3blocks-gaps.

**Comment by kopr12** [comment]
Yeah that was it, works now.

Wasn't paying attention, didn't saw that latest release (1.4) was released in July 2015.
Anyway, thanks!
