### ISSUE TITLE
How to put icons on i3blocks?

### ISSUE THREAD

**Issue by flashery** [Airblader/i3blocks-gaps#4]
Hello I am wondering for a few days now why my i3bar can’t display icons inside i3blocks. Right now when I copy some config from github like this one https://github.com/Algorithm79/Dotfiles_i3/blob/master/i3status/config.

It will display on my machine like this https://imgur.com/a/vhlK4. I don’t know why I can’t configure my machine the way they are.

Can you help me?

**Comment by Airblader** [comment]
I don't know what I'm missing, but I don't see an i3bar on that screenshot. In any case, you need to install the icon font (probably FontAwesome) and use it as the bar font for it to work.

Please use https://www.reddit.com/r/i3wm/ for support questions.
