### ISSUE TITLE
Cant make borders to work in i3blocks-gaps

### ISSUE THREAD

**Issue by flashery** [Airblader/i3blocks-gaps#5]
Hello I am trying to configure your plugin  on i3gaps which is also maintained by you. But I can't seems to make the borders work. Every time I add the borders it it will show an error "ErrorL status_command process exited unexpectedly (exit 1)"

My i3blocks config was copied from this link http://dotshare.it/dots/1430/1/raw/. The appearance of the config can be found here http://dotshare.it/dots/1430/

So I try to remove the borders and it works here is the result https://imgur.com/a/TWM2u. Its ugly I think maybe I need to add the borders but how?

Can you help?

**Comment by Airblader** [comment]
Closing in favor of the reddit thread you opened.
