### ISSUE TITLE
Any change of updating to match the base?

### ISSUE THREAD

**Issue by Ingvix** [Airblader/i3blocks-gaps#7]
I'd like to be able to use the borders but I'd also like to have unlimited character amount for label, which they fixed from the base but is not present in yours. Also they removed the automatic space at the end of label which I liked; more freedom for the user. So far didn't notice any other critical changes for my use. The limited label characters make it really hard to use pango markup as it often leaves the ending tag out. Any change of merging at least those things to your repo?

**Comment by Airblader** [comment]
AFAIK in the new i3blocks you no longer need this fork, as sending the borders should be supported already. Did you try just using i3blocks and specifying borders?

**Comment by Ingvix** [comment]
Oh, you're right. I must've messed up the syntax somehow when I tried earlier but now I got it to work. No problemo then.

**Comment by Airblader** [comment]
I should probably archive this repository, though, and recommend switching back to i3blocks :-)

**Comment by Ingvix** [comment]
That might be wise.

**Comment by Airblader** [comment]
I think the new i3blocks isn't actually released yet, did you install a source build now to get it to work?

**Comment by Ingvix** [comment]
Yup. First I installed from official Debian repo but then I noticed that the label length indeed was limited and then build the base myself after I learned that it was fixed in the latest. It was after that I learned from this repo and tried the borders in base build but messed something up. Tried this fork, got sad, changed back, got it working, got happy and here we are.
