### ISSUE TITLE
Is i3blocks-gaps obsolete?

### ISSUE THREAD

**Issue by xelra** [Airblader/i3blocks-gaps#8]
I'm new to the whole i3 world and still trying to wrap my head around how everything comes together.
I was reading some commits and I saw https://github.com/vivien/i3blocks/commit/d353d48f8043dd5b14b88fa939c015e8ada0f73c and was wondering whether i3blocks-gaps is obsolete now?

If so, I think it would make sense to write a new README that points people back to the original with a few lines of explanation.

**Comment by Airblader** [comment]
Yes, it will become obsolete, but only once those changes in i3blocks are actually released.
